global:
  scrape_interval: 10s
  scrape_timeout: 10s
  query_log_file: query_log_file.log

alerting:
  alertmanagers:
    - static_configs:
        - targets:

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/actuator/prometheus'
    scheme: 'http'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          service: 'server-monitor1'

  - job_name: 'exporter'
    metrics_path: '/metrics'
    scheme: 'http'
    static_configs:
      - targets: [ 'host.docker.internal:9100' ]
        labels:
          service: 'system-monitor1'