version: '3.7'

services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
  jtoon-blue:
    image: ${DOCKER_HUB_USERNAME}/${DOCKER_HUB_REPOSITORY}:latest
    container_name: jtoon-blue
    restart: always
    expose:
      - ${SERVER_PORT}
    depends_on:
      - redis
  jtoon-green:
    image: ${DOCKER_HUB_USERNAME}/${DOCKER_HUB_REPOSITORY}:latest
    container_name: jtoon-green
    restart: always
    expose:
      - ${SERVER_PORT}
    depends_on:
      - redis
  redis:
    image: redis:latest
    container_name: redis
    hostname: ${hostname}
    command: redis-server
    ports:
      - ${redis-inbound}:${redis-outbound}
    volumes:
      - ./redis/data/:/data
