jwt:
  secret:
    access-key: sf71U3iuhf2lkh!@jfAlqjhw3523fkjghqf23yfjAwDFfXbw
  iss: jtoon
  access-expire: 60
  refresh-expire: 10080

pg:
  kg-inicis:
    rest-api-key: 3223100750634733
    rest-api-secret: XzV7c0eS6Ege5o54YeWkcIAvEuKOIiZpGzlgunbRG6fzR0ddQJjMStW6vAmzR6wKmt5WzEFYSmd5H18P

spring:
  cloud:
    aws:
      region:
        static: ap-northeast-2
      s3:
        bucket: jtoon-webtoon-image-bucket
      cloud-front:
        url: https://d1l8zelitny4rh.cloudfront.net/
      credentials:
        access-key: AKIAYBF7QAGOTWO3GJFF
        secret-key: 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
      max-request-size: 20MB # 요청 당 최대 사이즈

  servlet:
    multipart:
      max-file-size: 10MB # 파일 하나 당 최대 사이즈
      max-request-size: 20MB # 요청 당 최대 사이즈

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jtoon-db?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: password

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: Naver
            client-id: q1v6WmCClOAFmyiilMak
            client-secret: q8IERmk6Wx
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            scope:
              - name
              - email
              - gender
              - mobile
              - nickname
        provider:
          naver:
            authorizationUri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

smtp:
  username: saeyun302@gmail.com
  password: uilqzqazijsryaob
  host: smtp.google.com
  port: 587

logging.level:
  org.hibernate.SQL: debug
